version: '3'

services:

  # Database service
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 9932:5432
    env_file:
      - .env
    # Add this section to run the initialization script
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - weather-api-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script

  # backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-weather-api
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      weather-api: ${weather_api}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  weather-api-data: